// Auto-generated spell data from homebrew markdown files
// Generated on: 2026-02-19T02:46:46.368Z
// DO NOT EDIT THIS FILE MANUALLY

import type { Spell } from "./types";

export const HOMEBREW_SPELLS: Spell[] = [
  {
    "id": "bite-of-the-weretiger",
    "name": "Bite of the Weretiger",
    "school": "Transmutation",
    "level": {
      "Druid": 5,
      "Sorcerer": 6,
      "Wizard": 6
    },
    "components": "V, S, M",
    "castingTime": "1 standard action",
    "range": "Personal",
    "duration": "1 round/level",
    "savingThrow": "",
    "spellResistance": "",
    "description": "You snarl, and your features shift into those of a tiger. Your hands grow sharp claws, and the thick skin and striped fur of a tiger covers your body.\n\nYou gain a +12 enhancement bonus to Strength, a +4 enhancement bonus to Dexterity, a +6 enhancement bonus to Constitution, and a +5 enhancement bonus to natural armor. Your hands become claws, granting you two claw attacks, and your mouth becomes that of a tiger, giving you a bite attack. You can attack with both claws at your full base attack bonus, but your bite attack takes a –2 penalty (as if you had the Multiattack feat). Each claw deals 1d8 points of damage (1d6 if you are Small) + your Str modifier, and your bite deals 2d6 points of damage (2d6 if you are Small) + 1/2 your Str modifier. You gain the benefits of the Blind-Fight and Power Attack feats, as well. If your base attack bonus is +6 or higher, you do not gain any additional attacks.",
    "source": "Spell Compendium (SC) Spells",
    "target": "You",
    "materialComponent": "A tiger’s claw."
  },
  {
    "id": "wall-of-good",
    "name": "Wall of Good",
    "school": "Abjuration",
    "level": {
      "Cleric": 4,
      "Sorcerer": 4,
      "Wizard": 4
    },
    "components": "V, S, M/DF",
    "castingTime": "1 standard action",
    "range": "Close (25 ft. + 5 ft./2 levels)",
    "duration": "10 minutes/level",
    "savingThrow": "See text",
    "spellResistance": "Yes",
    "description": "You invoke the abjuration, and a cascade of brilliant white energy springs up in a wall that becomes invisible almost instantly.\n\nYou create an immobile barrier that inhibits evil creatures. An evil summoned creature cannot pass through the wall in either direction, and any other evil creature must succeed on a Will save each time it attempts to move through the wall. If the saving throw is failed, the creature’s movement is stopped, and it can take no other action that round.\n\nA wall of good must be continuous and unbroken when formed. If it is cast so that an object or creature breaks its surface, the spell fails.",
    "source": "Spell Compendium (SC) Spells",
    "descriptor": "Good",
    "effect": "A straight wall whose area is up to one 10-ft. square/level or a sphere or hemisphere with a radius of up to 5 ft./2 levels",
    "arcaneMaterialComponent": "Powdered silver worth 25 gp."
  },
  {
    "id": "wrinkle-reality",
    "name": "Wrinkle Reality",
    "school": "Transmutation",
    "level": {
      "Sorcerer": 9,
      "Wizard": 9
    },
    "components": "V, S",
    "castingTime": "1 full-round action",
    "range": "30 ft.",
    "duration": "Concentration",
    "savingThrow": "Fortitude and Reflex and Will; see text",
    "spellResistance": "No",
    "description": "You cause reality to wrinkle and fold in upon itself in a poly-dimensional twist. Geometry and physics within 30 feet seem to follow different laws. Anyone within the emanation, including you, must save each round, regardless of previous success or failure, or be sickened (Fortitude save), slowed (Reflex save), and frightened (Will save).  These saves are required on the creature's turn if the creature was within the emanation at all since its last turn or enters the emanation at all on the current turn.  Furthermore, the emanation counts as a distracting spell, thus requiring Concentration checks.  You receive a +4 bonus to the aforementioned saves and checks.\n\nFurther effects within the emanation occur randomly based on a 1d12 roll each round.\n\n| d12 | Effect                                                                  |\n| --- | ----------------------------------------------------------------------- |\n| 1   | A passageway/hole permanently opens where none existed before.          |\n| 2   | A passageway/hole permanently closes.                                   |\n| 3   | The largest rigid object suffers 10d12 damage, bypassing hardness.      |\n| 4   | A random object is permanently reduced to half its size.                |\n| 5   | A random object is permanently enlarged to twice its size.              |\n| 6   | Gravity is reversed for one round, as per spell.                        |\n| 7   | A random creature is aged 10 years, no save.                            |\n| 8   | Every creature shifts 5 ft. in a random direction, determined by d8.    |\n| 9   | One random creature becomes insane, Will save DC 25.                    |\n| 10  | One random creature is flipped inside-out, dying, Fortitude save DC 25. |\n| 11  | Everything is gated to the Far Realms, Reflex save DC 25.               |\n| 12  | Roll twice more; this is cumulative.                                    |",
    "source": "Dragonvale (DV) Spells",
    "area": "Emanation"
  }
];
