import type { Spell } from "./types";

// Sample spell data - this will be expanded with more spells
// For a full implementation, you would parse the HTML files in spells-srd directory
export const SPELLS: Spell[] = [
  {
    id: "acid-arrow",
    name: "Acid Arrow",
    school: "Conjuration",
    subschool: "Creation",
    descriptor: "Acid",
    level: { Sorcerer: 2, Wizard: 2 },
    components: "V, S, M, F",
    castingTime: "1 standard action",
    range: "Long (400 ft. + 40 ft./level)",
    effect: "One arrow of acid",
    duration: "1 round + 1 round per three levels",
    savingThrow: "None",
    spellResistance: "No",
    description:
      "A magical arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels (to a maximum of 18th), the acid, unless somehow neutralized, lasts for another round, dealing another 2d4 points of damage in that round.",
    materialComponent: "Powdered rhubarb leaf and an adder's stomach.",
    focus: "A dart.",
  },
  {
    id: "aid",
    name: "Aid",
    school: "Enchantment",
    subschool: "Compulsion",
    descriptor: "Mind-Affecting",
    level: { Cleric: 2 },
    components: "V, S, DF",
    castingTime: "1 standard action",
    range: "Touch",
    target: "Living creature touched",
    duration: "1 min./level",
    savingThrow: "None",
    spellResistance: "Yes (harmless)",
    description:
      "Aid grants the target a +1 morale bonus on attack rolls and saves against fear effects, plus temporary hit points equal to 1d8 + caster level (to a maximum of 1d8+10 temporary hit points at caster level 10th).",
  },
  {
    id: "air-walk",
    name: "Air Walk",
    school: "Transmutation",
    descriptor: "Air",
    level: { Cleric: 4, Druid: 4 },
    components: "V, S, DF",
    castingTime: "1 standard action",
    range: "Touch",
    target: "Creature (Gargantuan or smaller) touched",
    duration: "10 min./level",
    savingThrow: "None",
    spellResistance: "Yes (harmless)",
    description:
      "The subject can tread on air as if walking on solid ground. Moving upward is similar to walking up a hill. The maximum upward or downward angle possible is 45 degrees, at a rate equal to one-half the air walker's normal speed.",
  },
  {
    id: "alarm",
    name: "Alarm",
    school: "Abjuration",
    level: { Bard: 1, Ranger: 1, Sorcerer: 1, Wizard: 1 },
    components: "V, S, F/DF",
    castingTime: "1 standard action",
    range: "Close (25 ft. + 5 ft./2 levels)",
    area: "20-ft.-radius emanation centered on a point in space",
    duration: "2 hours/level (D)",
    savingThrow: "None",
    spellResistance: "No",
    description:
      "Alarm sounds a mental or audible alarm each time a creature of Tiny or larger size enters the warded area or touches it. A creature that speaks the password (determined by you at the time of casting) does not set off the alarm.",
    arcaneFocus: "A tiny bell and a piece of very fine silver wire",
  },
  {
    id: "animal-growth",
    name: "Animal Growth",
    school: "Transmutation",
    level: { Druid: 5, Ranger: 4, Sorcerer: 5, Wizard: 5 },
    components: "V, S",
    castingTime: "1 standard action",
    range: "Medium (100 ft. + 10 ft./level)",
    target:
      "Up to one animal (Gargantuan or smaller) per two levels, no two of which can be more than 30 ft. apart",
    duration: "1 min./level",
    savingThrow: "Fortitude negates",
    spellResistance: "Yes",
    description:
      "A number of animals grow to twice their normal size and eight times their normal weight. This alteration changes each animal's size category to the next largest, grants it a +8 size bonus to Strength and a +4 size bonus to Constitution (and thus an extra 2 hit points per HD), and imposes a -2 size penalty to Dexterity.",
  },
  {
    id: "bless",
    name: "Bless",
    school: "Enchantment",
    subschool: "Compulsion",
    descriptor: "Mind-Affecting",
    level: { Cleric: 1, Paladin: 1 },
    components: "V, S, DF",
    castingTime: "1 standard action",
    range: "50 ft.",
    area: "The caster and all allies within a 50-ft. burst, centered on the caster",
    duration: "1 min./level",
    savingThrow: "None",
    spellResistance: "Yes (harmless)",
    description:
      "Bless fills your allies with courage. Each ally gains a +1 morale bonus on attack rolls and on saving throws against fear effects.",
  },
  {
    id: "cure-light-wounds",
    name: "Cure Light Wounds",
    school: "Conjuration",
    subschool: "Healing",
    level: { Bard: 1, Cleric: 1, Druid: 1, Paladin: 1, Ranger: 2 },
    components: "V, S",
    castingTime: "1 standard action",
    range: "Touch",
    target: "Creature touched",
    duration: "Instantaneous",
    savingThrow: "Will half (harmless); see text",
    spellResistance: "Yes (harmless); see text",
    description:
      "When laying your hand upon a living creature, you channel positive energy that cures 1d8 points of damage +1 point per caster level (maximum +5). Since undead are powered by negative energy, this spell deals damage to them instead of curing their wounds. A Will save halves this damage.",
  },
  {
    id: "detect-magic",
    name: "Detect Magic",
    school: "Divination",
    level: { Bard: 0, Cleric: 0, Druid: 0, Sorcerer: 0, Wizard: 0 },
    components: "V, S",
    castingTime: "1 standard action",
    range: "60 ft.",
    area: "Cone-shaped emanation",
    duration: "Concentration, up to 1 min./level (D)",
    savingThrow: "None",
    spellResistance: "No",
    description:
      "You detect magical auras. The amount of information revealed depends on how long you study a particular area or subject.",
  },
  {
    id: "fireball",
    name: "Fireball",
    school: "Evocation",
    descriptor: "Fire",
    level: { Sorcerer: 3, Wizard: 3 },
    components: "V, S, M",
    castingTime: "1 standard action",
    range: "Long (400 ft. + 40 ft./level)",
    area: "20-ft.-radius spread",
    duration: "Instantaneous",
    savingThrow: "Reflex half",
    spellResistance: "Yes",
    description:
      "A fireball spell is an explosion of flame that detonates with a low roar and deals 1d6 points of fire damage per caster level (maximum 10d6) to every creature within the area. Unattended objects also take this damage. The explosion creates almost no pressure.",
    materialComponent: "A tiny ball of bat guano and sulfur.",
  },
  {
    id: "magic-missile",
    name: "Magic Missile",
    school: "Evocation",
    descriptor: "Force",
    level: { Sorcerer: 1, Wizard: 1 },
    components: "V, S",
    castingTime: "1 standard action",
    range: "Medium (100 ft. + 10 ft./level)",
    target:
      "Up to five creatures, no two of which can be more than 15 ft. apart",
    duration: "Instantaneous",
    savingThrow: "None",
    spellResistance: "Yes",
    description:
      "A missile of magical energy darts forth from your fingertip and strikes its target, dealing 1d4+1 points of force damage. The missile strikes unerringly, even if the target is in melee combat or has less than total cover or total concealment. For every two caster levels beyond 1st, you gain an additional missile—two at 3rd level, three at 5th, four at 7th, and the maximum of five missiles at 9th level or higher.",
  },
];
